---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-monitor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: service-monitors
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: v1.1
  name: service-monitor-{{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: service-monitors
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: v1.2
  name: service-monitor-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-monitor-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: service-monitor-sa
  namespace: {{ .Release.Namespace }}
